# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-12 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_time',
        ),
    ]
