# Generated by Django 2.0 on 2018-03-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20171212_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Question'),
        ),
    ]
