# Generated by Django 2.0 on 2018-03-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_accesstoken_basicanalytic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='ige_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='ige_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='igt_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='igt_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='igv_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='igv_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='oge_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='oge_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='ogt_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='ogt_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='ogv_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='ogv_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='total_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='total_finished',
            field=models.IntegerField(default=0),
        ),
    ]
