# Generated by Django 2.0 on 2018-03-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20180310_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
