# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-12 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20171212_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current_survey_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 12, 12, 13, 12, 4, 128083)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 12, 12, 13, 12, 4, 128041)),
        ),
    ]
