# Generated by Django 2.0 on 2018-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20180310_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalytic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='office_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicanalytic',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='first_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='initiated_conversation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='second_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='third_question',
            field=models.BooleanField(default=False),
        ),
    ]
