# Generated by Django 2.0 on 2018-03-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20180310_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='basic_analytic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.BasicAnalytic'),
        ),
    ]
