# Generated by Django 2.0 on 2018-03-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_coreuser_basic_analytic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicanalytic',
            name='office_id',
        ),
    ]
