# Generated by Django 2.0 on 2018-03-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_basicanalytic_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='relative_analytic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relative_analytic', to='bot.BasicAnalytic'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='basic_analytic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_analytic', to='bot.BasicAnalytic'),
        ),
    ]
