# Generated by Django 2.0 on 2018-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20180310_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
