# Generated by Django 2.0 on 2018-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_coreuser_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='daal',
            name='product',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
